version: "3.8"

services:
  timesheet-app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/timesheet-devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: timesheet-devops
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
